# For full config options, check the docs:
#   https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: oss-metrics-dashboard

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'development'} # development, production
  region: ${opt:region, 'us-east-1'}
  stackTags:
    service: ${self:service} # required tag
    Environment: ${self:provider.stage} # required tag
    Owner: Tophat OSS # required tag

functions:
  github:
    handler: src/github.handle_cron
    events:
      - schedule: rate(1 day)
  npm:
    handler: src/npm.handle_cron
    events:
      - schedule: rate(1 day)

package:
  exclude:
    - '**'
  include:
    - 'src/**'
    - '!src/tests/**'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
